name: codacy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-330.0.dev

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  husky: ^0.1.7
  lint_staged: ^0.5.1

flutter:
  uses-material-design: true
  
lint_staged:
  'lib/**.dart': dart format -l 120 && dart analyze --fatal-infos --fatal-warnings
