name: Check Unsupported Files and Lint Scripts

on: [push, pull_request]

jobs:
  check-unsupported-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck

    - name: Lint shell scripts
      run: |
        shellcheck -x .husky/pre-commit

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.26.0'

    - name: Display Flutter version
      run: flutter --version

    - name: Validate Flutter version
      run: |
        EXPECTED_VERSION="3.26.0"
        INSTALLED_VERSION=$(flutter --version | grep 'Flutter' | awk '{print $2}')
        if [ "$INSTALLED_VERSION" != "$EXPECTED_VERSION" ]; then
          echo "Installed Flutter version ($INSTALLED_VERSION) does not match expected version ($EXPECTED_VERSION)"
          exit 1
        else
          echo "Flutter version is valid: $INSTALLED_VERSION"
        fi

    - name: Check for unsupported files
      run: |
        echo "Checking for unsupported files in the lib folder..."
        UNSUPPORTED_FILES=$(find lib -type f -not \( -name "*.dart" -o -name "*.json" \))
        
        if [ -n "$UNSUPPORTED_FILES" ]; then
          echo "Unsupported files found in the lib folder:"
          echo "$UNSUPPORTED_FILES"
          exit 1
        else
          echo "No unsupported files found."
        fi
